import os
import re
import sqlite3
from typing import Optional

try:
    import psycopg
except Exception:  # pragma: no cover - optional dependency until installed
    psycopg = None


def resolve_database_target(db_path: Optional[str] = None) -> str:
    return os.environ.get("DATABASE_URL") or db_path or "database/faces_improved.db"


def is_postgres_target(db_path: Optional[str] = None) -> bool:
    target = str(resolve_database_target(db_path)).strip().lower()
    return target.startswith(("postgres://", "postgresql://", "postgres+", "postgresql+"))


def _normalize_postgres_dsn_for_driver(target: str) -> str:
    normalized = str(target).strip()
    if "://" not in normalized:
        return normalized
    scheme, rest = normalized.split("://", 1)
    if "+" in scheme:
        scheme = scheme.split("+", 1)[0]
    return f"{scheme}://{rest}"


def connect(db_path: Optional[str] = None):
    target = resolve_database_target(db_path)
    if is_postgres_target(target):
        if psycopg is None:
            raise RuntimeError("PostgreSQL selected but `psycopg` is not installed.")
        raw = psycopg.connect(_normalize_postgres_dsn_for_driver(target))
        return CompatConnection(raw, "postgres")
    raw = sqlite3.connect(target, timeout=30.0)
    _configure_sqlite_connection(raw)
    return CompatConnection(raw, "sqlite")


def table_columns(conn, table_name: str) -> set[str]:
    if getattr(conn, "dialect", "sqlite") == "postgres":
        cur = conn.cursor()
        cur.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = %s
            ORDER BY ordinal_position
            """,
            (table_name,),
        )
        rows = cur.fetchall()
        return {row[0] for row in rows}

    cur = conn.cursor()
    cur.execute(f"PRAGMA table_info({table_name})")
    rows = cur.fetchall()
    return {row[1] for row in rows}


class CompatConnection:
    def __init__(self, raw, dialect: str):
        self._raw = raw
        self.dialect = dialect

    def cursor(self):
        return CompatCursor(self._raw.cursor(), self.dialect)

    def commit(self):
        return self._raw.commit()

    def close(self):
        return self._raw.close()

    def rollback(self):
        return self._raw.rollback()

    def __getattr__(self, name):
        return getattr(self._raw, name)


class CompatCursor:
    def __init__(self, raw, dialect: str):
        self._raw = raw
        self.dialect = dialect
        self.lastrowid = None

    def execute(self, query, params=None):
        if self.dialect == "postgres":
            query = _translate_sqlite_to_postgres(query)
            params = _normalize_params(params)
        result = self._raw.execute(query, params or ())
        self.lastrowid = getattr(self._raw, "lastrowid", None)
        return result

    def executemany(self, query, seq_of_params):
        if self.dialect == "postgres":
            query = _translate_sqlite_to_postgres(query)
        result = self._raw.executemany(query, seq_of_params)
        self.lastrowid = getattr(self._raw, "lastrowid", None)
        return result

    def fetchone(self):
        return self._raw.fetchone()

    def fetchall(self):
        return self._raw.fetchall()

    def __iter__(self):
        return iter(self._raw)

    def __getattr__(self, name):
        return getattr(self._raw, name)


def _normalize_params(params):
    if params is None:
        return ()
    if isinstance(params, tuple):
        return params
    if isinstance(params, list):
        return tuple(params)
    return (params,)


def _configure_sqlite_connection(conn: sqlite3.Connection) -> None:
    # WAL mode allows long-running analytics reads and import writes
    # to coexist more reliably than SQLite's default rollback journal.
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=30000")
    conn.execute("PRAGMA synchronous=NORMAL")
    conn.execute("PRAGMA foreign_keys=ON")


def _translate_sqlite_to_postgres(query: str) -> str:
    translated = query
    translated = translated.replace("?", "%s")
    translated = translated.replace("BLOB", "BYTEA")
    translated = translated.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    translated = translated.replace("VALUES (%s, %s) ON CONFLICT(key) DO UPDATE SET value = excluded.value", "VALUES (%s, %s) ON CONFLICT(key) DO UPDATE SET value = EXCLUDED.value")
    translated = translated.replace("UPDATE staff_accounts SET is_active = NOT is_active WHERE staff_id = %s", "UPDATE staff_accounts SET is_active = CASE WHEN COALESCE(is_active, 0) = 0 THEN 1 ELSE 0 END WHERE staff_id = %s")

    translated = re.sub(r"PRAGMA table_info\(([^)]+)\)", _translate_pragma_table_info, translated, flags=re.IGNORECASE)
    translated = translated.replace("DATE('now', '-13 days')", "CURRENT_DATE - INTERVAL '13 days'")
    translated = translated.replace("DATE('now', 'start of month', '-5 months')", "date_trunc('month', CURRENT_DATE) - INTERVAL '5 months'")
    translated = translated.replace("DATE('now')", "CURRENT_DATE")
    translated = translated.replace("strftime('%Y-%m', timestamp)", "TO_CHAR(timestamp, 'YYYY-MM')")
    translated = translated.replace("strftime('%H', timestamp)", "EXTRACT(HOUR FROM timestamp)")
    translated = translated.replace("strftime('%w', timestamp)", "EXTRACT(DOW FROM timestamp)")
    translated = re.sub(r"CAST\(EXTRACT\((HOUR|DOW) FROM ([^)]+)\) AS INTEGER\)", r"EXTRACT(\1 FROM \2)::int", translated)
    translated = translated.replace("CAST(EXTRACT(HOUR FROM timestamp) AS INTEGER)", "EXTRACT(HOUR FROM timestamp)::int")
    translated = translated.replace("CAST(EXTRACT(DOW FROM timestamp) AS INTEGER)", "EXTRACT(DOW FROM timestamp)::int")
    return translated


def _translate_pragma_table_info(match):
    table_name = match.group(1).strip().strip("'\"")
    return (
        "SELECT ordinal_position - 1 AS cid, column_name, data_type, "
        "is_nullable, column_default, NULL "
        f"FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '{table_name}' "
        "ORDER BY ordinal_position"
    )
