"""Add occupancy_alerts table for capacity notifications.

Revision ID: 20260502_0008
Revises: 20260502_0007
Create Date: 2026-05-02 00:00:03.000000
"""
from __future__ import annotations

from alembic import op


revision = "20260502_0008"
down_revision = "20260502_0007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS occupancy_alerts (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            alert_type TEXT NOT NULL,
            level TEXT NOT NULL,
            message TEXT NOT NULL,
            occupancy_count INTEGER NOT NULL,
            capacity_limit INTEGER NOT NULL,
            occupancy_ratio REAL NOT NULL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            state_date TEXT NOT NULL,
            dismissed_at TIMESTAMP,
            dismissed_by TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_occupancy_alerts_created_at_desc ON occupancy_alerts(created_at DESC)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_occupancy_alerts_active_date ON occupancy_alerts(alert_type, state_date, dismissed_at)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS idx_occupancy_alerts_active_date")
    op.execute("DROP INDEX IF EXISTS idx_occupancy_alerts_created_at_desc")
    op.execute("DROP TABLE IF EXISTS occupancy_alerts")

