"""remove legacy recognition_log table

Revision ID: 20260504_0011
Revises: 20260503_0010
Create Date: 2026-05-04
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20260504_0011"
down_revision = "20260503_0010"
branch_labels = None
depends_on = None


def _table_exists(bind: sa.Connection, table_name: str) -> bool:
    row = bind.execute(
        sa.text(
            """
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = 'public'
              AND table_name = :table_name
            """
        ),
        {"table_name": table_name},
    ).fetchone()
    return row is not None


def upgrade() -> None:
    bind = op.get_bind()

    if _table_exists(bind, "recognition_log"):
        op.execute(
            """
            INSERT INTO recognition_events (
                event_id, user_id, sr_code, decision, event_type, confidence,
                primary_confidence, secondary_confidence, primary_distance, secondary_distance,
                face_quality, method, captured_at, payload_json
            )
            SELECT
                'legacy-log-' || r.log_id::text AS event_id,
                r.user_id,
                u.sr_code,
                'allowed' AS decision,
                'entry' AS event_type,
                r.confidence,
                r.primary_confidence,
                r.secondary_confidence,
                r.primary_distance,
                r.secondary_distance,
                r.face_quality,
                COALESCE(NULLIF(TRIM(r.method), ''), 'two-factor') AS method,
                r.timestamp AS captured_at,
                json_build_object('source', 'postgres_recognition_log', 'legacy_log_id', r.log_id)::text AS payload_json
            FROM recognition_log r
            LEFT JOIN users u ON u.user_id = r.user_id
            ON CONFLICT(event_id) DO NOTHING
            """
        )
        op.execute("DROP TABLE recognition_log")

    op.execute(
        """
        DELETE FROM app_settings
        WHERE key = 'event_model_legacy'
        """
    )
    op.execute(
        """
        INSERT INTO app_settings (key, value)
        VALUES ('event_model_canonical', 'recognition_events')
        ON CONFLICT(key) DO UPDATE SET value = EXCLUDED.value
        """
    )


def downgrade() -> None:
    bind = op.get_bind()
    if not _table_exists(bind, "recognition_log"):
        op.execute(
            """
            CREATE TABLE recognition_log (
                log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER,
                confidence DOUBLE PRECISION,
                timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                primary_confidence DOUBLE PRECISION,
                secondary_confidence DOUBLE PRECISION,
                primary_distance DOUBLE PRECISION,
                secondary_distance DOUBLE PRECISION,
                face_quality DOUBLE PRECISION,
                method TEXT DEFAULT 'two-factor',
                CONSTRAINT recognition_log_user_id_fkey
                    FOREIGN KEY (user_id) REFERENCES users(user_id)
                    ON DELETE SET NULL
                    ON UPDATE NO ACTION
            )
            """
        )
        op.execute("CREATE INDEX idx_recognition_log_user_id ON recognition_log(user_id)")
        op.execute("CREATE INDEX idx_recognition_log_timestamp ON recognition_log(timestamp)")

    op.execute(
        """
        INSERT INTO app_settings (key, value)
        VALUES ('event_model_legacy', 'recognition_log_compatibility_layer_only')
        ON CONFLICT(key) DO NOTHING
        """
    )
